export const ADD_POST_FIRST = `ADD_POST_FIRST`
export const ADD_POST_SUCCESS = `ADD_POST_SUCCESS`
export const ADD_POST_FAIL = `ADD_POST_FAIL`

export const GET_POST_FIRST = `GET_POST_FIRST`
export const GET_POST_SUCCESS = `GET_POST_SUCCESS`
export const GET_POST_FAIL = `GET_POST_FAIL`

export const GET_USER_POSTS_FIRST = `GET_USER_POSTS_FIRST`
export const GET_USER_POSTS_SUCCESS = `GET_USER_POSTS_SUCCESS`
export const GET_USER_POSTS_FAIL = `GET_USER_POSTS_FAIL`

export const GET_USER_SINGLE_PAGE_FIRST=`GET_USER_SINGLE_PAGE_FIRST`
export const GET_USER_SINGLE_PAGE_SUCCESS=`GET_USER_SINGLE_PAGE_SUCCESS`
export const GET_USER_SINGLE_PAGE_FAIL=`GET_USER_SINGLE_PAGE_FAIL`

export const LIKE_USER_POST=`LIKE_USER_POST`
export const UNLIKE_USER_POST =`UNLIKE_USER_POST`

export const USER_POSTS_LIKE=`USER_POSTS_LIKE`
export const USER_POSTS_UNLIKE=`USER_POSTS_UNLIKE`
export const SINGLE_PAGE_LIKE=`SINGLE_PAGE_LIKE`
export const SINGLE_PAGE_UNLIKE=`SINGLE_PAGE_UNLIKE`

export const ADD_REPLY_TO_POST_SUCCESS=`ADD_REPLY_TO_POST_SUCCESS`
export const ADD_REPLY_TO_POST_FAIL=`ADD_REPLY_TO_POST_FAIL`

export const GET_REPlY_POST_SUCCESS=`GET_REPlY_POST_SUCCESS`