export const REGISTER_FIRST=`REGISTER_FIRST`
export const REGISTER_SUCCESS=`REGISTER_SUCCESS`
export const REGISTER_FAIL=`REGISTER_FAIL`

export const LOGIN_FIRST=`LOGIN_FIRST`
export const LOGIN_SUCCESS=`LOGIN_SUCCESS`
export const LOGIN_FAIL=`LOGIN_FAIL`

export const LOGOUT_FIRST=`LOGOUT_FIRST`
export const LOGOUT_SUCCESS=`LOGOUT_SUCCESS`
export const LOGOUT_FAIL=`LOGOUT_FAIL`

export const ALL_FIRST=`ALL_FIRST`
export const ALL_SUCCESS=`ALL_SUCCESS`
export const ALL_FAIL=`ALL_FAIL`

export const IMAGES_SUCCESS=`IMAGES_SUCCESS`

export const GET_USER_DATA_FIRST=`GET_USER_DATA_FIRST`
export const GET_USER_DATA_SUCCESS=`GET_USER_DATA_SUCCESS`
export const GET_USER_DATA_FAIL=`GET_USER_DATA_FAIL`

export const CHANGE_PROFILE_IMAGE_FIRST=`CHANGE_PROFILE_IMAGE_FIRST`
export const CHANGE_PROFILE_IMAGE_SUCCESS=`CHANGE_PROFILE_IMAGE_SUCCESS`
export const CHANGE_PROFILE_IMAGE_FAIL=`CHANGE_PROFILE_IMAGE_FAIL`

export const CHANGE_COVER_IMAGE_FIRST=`CHANGE_COVER_IMAGE_FIRST`
export const CHANGE_COVER_IMAGE_SUCCESS=`CHANGE_COVER_IMAGE_SUCCESS`
export const CHANGE_COVER_IMAGE_FAIL=`CHANGE_COVER_IMAGE_FAIL`

export const CHANGE_BIO_FIRST=`CHANGE_BIO_FIRST`
export const CHANGE_BIO_SUCCESS=`CHANGE_BIO_SUCCESS`
export const CHANGE_BIO_FAIL=`CHANGE_BIO_FAIL`

export const CHANGE_FIRSTNAME_FIRST=`CHANGE_FIRSTNAME_FIRST`
export const CHANGE_FIRSTNAME_SUCCESS=`CHANGE_FIRSTNAME_SUCCESS`
export const CHANGE_FIRSTNAME_FAIL=`CHANGE_FIRSTNAME_FAIL`

