export const REGISTER_FIRST=`REGISTER_FIRST`
export const REGISTER_SUCCESS=`REGISTER_SUCCESS`
export const REGISTER_FAIL=`REGISTER_FAIL`

export const LOGIN_FIRST=`LOGIN_FIRST`
export const LOGIN_SUCCESS=`LOGIN_SUCCESS`
export const LOGIN_FAIL=`LOGIN_FAIL`

export const LOGOUT_FIRST=`LOGOUT_FIRST`
export const LOGOUT_SUCCESS=`LOGOUT_SUCCESS`
export const LOGOUT_FAIL=`LOGOUT_FAIL`

export const ALL_FIRST=`ALL_FIRST`
export const ALL_SUCCESS=`ALL_SUCCESS`
export const ALL_FAIL=`ALL_FAIL`

