export const OPEN_LOGIN_FORM=`OPEN_LOGIN_FORM`
export const CLOSE_LOGIN_FORM=`CLOSE_LOGIN_FORM`

export const OPEN_REGISTER_FORM=`OPEN_REGISTER_FORM`
export const CLOSE_REGISTER_FORM=`CLOSE_REGISTER_FORM`


export const OPEN_EDIT_FORM=`OPEN_EDIT_FORM`
export const CLOSE_EDIT_FORM=`CLOSE_EDIT_FORM`

export const OPEN_TWEET_FORM = `OPEN_TWEET_FORM`
export const CLOSE_TWEET_FORM = `CLOSE_TWEET_FORM`