export const OPEN_LOGIN_FORM=`OPEN_LOGIN_FORM`
export const CLOSE_LOGIN_FORM=`CLOSE_LOGIN_FORM`

export const OPEN_REGISTER_FORM=`OPEN_REGISTER_FORM`
export const CLOSE_REGISTER_FORM=`CLOSE_REGISTER_FORM`