export const CREATE_STORE_FIRST=`CREATE_STORE_FIRST`
export const CREATE_STORE_SUCCESS=`CREATE_STORE_SUCCESS`
export const CREATE_STORE_FAIL=`CREATE_STORE_FAIL`

export const GET_STORE_SUCCESS="GET_STORE_SUCCESS"
export const GET_STORE_FAIL="GET_STORE_FAIL"
export const GET_STORE_FIRST="GET_STORE_FIRST"